/* Generated by icons.build.mjs from lucide-static 1.41.0 (ISC). Do not edit: change the
   subset in icons.build.mjs and run `pnpm icons:build`.

   icon(meaning) returns one <svg> string for server-rendered TypeScript and template literals;
   <ui-icon name="gain"> does the same for static HTML and Electron with no build step. Both
   draw at 24 and are scaled by --icon-size, stroked with currentColor, and hidden from
   assistive technology unless given a label. A <ui-icon data-morph> asked for another meaning
   keeps the paths it already drew and changes their shape into the new glyph's. */

import { drawGlyph, morphGlyph } from "./glyph-morph.js";

const ICON_SOURCE = {
  "gain": ["trending-up", '<path d="M16 7h6v6"/><path d="m22 7-8.5 8.5-5-5L2 17"/>'],
  "loss": ["trending-down", '<path d="M16 17h6v-6"/><path d="m22 17-8.5-8.5-5 5L2 7"/>'],
  "success": ["circle-check", '<circle cx="12" cy="12" r="10"/><path d="m16 9-5.5 5.5L8 12"/>'],
  "warning": ["triangle-alert", '<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"/><path d="M12 9v4"/><path d="M12 17h.01"/>'],
  "error": ["circle-x", '<circle cx="12" cy="12" r="10"/><path d="m15 9-6 6"/><path d="m9 9 6 6"/>'],
  "info": ["info", '<circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/>'],
  "guarded": ["shield-check", '<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/><path d="m9 12 2 2 4-4"/>'],
  "connected": ["wifi", '<path d="M12 20h.01"/><path d="M2 8.82a15 15 0 0 1 20 0"/><path d="M5 12.859a10 10 0 0 1 14 0"/><path d="M8.5 16.429a5 5 0 0 1 7 0"/>'],
  "disconnected": ["wifi-off", '<path d="M12 20h.01"/><path d="M8.5 16.429a5 5 0 0 1 7 0"/><path d="M5 12.859a10 10 0 0 1 5.17-2.69"/><path d="M19 12.859a10 10 0 0 0-2.007-1.523"/><path d="M2 8.82a15 15 0 0 1 4.177-2.643"/><path d="M22 8.82a15 15 0 0 0-11.288-3.764"/><path d="m2 2 20 20"/>'],
  "recording": ["circle-dot", '<circle cx="12" cy="12" r="1"/><circle cx="12" cy="12" r="10"/>'],
  "paused": ["circle-pause", '<circle cx="12" cy="12" r="10"/><line x1="10" x2="10" y1="15" y2="9"/><line x1="14" x2="14" y1="15" y2="9"/>'],
  "loading": ["loader-circle", '<path d="M21 12a9 9 0 1 1-6.219-8.56"/>'],
  "play": ["play", '<path d="M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z"/>'],
  "pause": ["pause", '<rect x="14" y="3" width="5" height="18" rx="1"/><rect x="5" y="3" width="5" height="18" rx="1"/>'],
  "stop": ["square", '<rect width="18" height="18" x="3" y="3" rx="2"/>'],
  "image": ["image", '<rect width="18" height="18" x="3" y="3" rx="2" ry="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/>'],
  "image-error": ["image-off", '<line x1="2" x2="22" y1="2" y2="22"/><path d="M10.41 10.41a2 2 0 1 1-2.83-2.83"/><line x1="13.5" x2="6" y1="13.5" y2="21"/><line x1="18" x2="21" y1="12" y2="15"/><path d="M3.59 3.59A1.99 1.99 0 0 0 3 5v14a2 2 0 0 0 2 2h14c.55 0 1.052-.22 1.41-.59"/><path d="M21 15V5a2 2 0 0 0-2-2H9"/>'],
  "add": ["plus", '<path d="M5 12h14"/><path d="M12 5v14"/>'],
  "remove": ["minus", '<path d="M5 12h14"/>'],
  "close": ["x", '<path d="M18 6 6 18"/><path d="m6 6 12 12"/>'],
  "check": ["check", '<path d="M20 6 9 17l-5-5"/>'],
  "search": ["search", '<path d="m21 21-4.34-4.34"/><circle cx="11" cy="11" r="8"/>'],
  "filter": ["funnel", '<path d="M10 20a1 1 0 0 0 .553.895l2 1A1 1 0 0 0 14 21v-7a2 2 0 0 1 .517-1.341L21.74 4.67A1 1 0 0 0 21 3H3a1 1 0 0 0-.742 1.67l7.225 7.989A2 2 0 0 1 10 14z"/>'],
  "settings": ["settings", '<path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"/><circle cx="12" cy="12" r="3"/>'],
  "more": ["ellipsis", '<circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/>'],
  "menu": ["menu", '<path d="M4 5h16"/><path d="M4 12h16"/><path d="M4 19h16"/>'],
  "edit": ["pencil", '<path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"/><path d="m15 5 4 4"/>'],
  "delete": ["trash-2", '<path d="M10 11v6"/><path d="M14 11v6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/><path d="M3 6h18"/><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>'],
  "copy": ["copy", '<rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/>'],
  "export": ["download", '<path d="M12 15V3"/><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><path d="m7 10 5 5 5-5"/>'],
  "import": ["upload", '<path d="M12 3v12"/><path d="m17 8-5-5-5 5"/><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>'],
  "refresh": ["refresh-cw", '<path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"/><path d="M21 3v5h-5"/><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"/><path d="M8 16H3v5"/>'],
  "reorder": ["grip-vertical", '<circle cx="9" cy="12" r="1"/><circle cx="9" cy="5" r="1"/><circle cx="9" cy="19" r="1"/><circle cx="15" cy="12" r="1"/><circle cx="15" cy="5" r="1"/><circle cx="15" cy="19" r="1"/>'],
  "external": ["external-link", '<path d="M15 3h6v6"/><path d="M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>'],
  "chevron-start": ["chevron-left", '<path d="m15 18-6-6 6-6"/>'],
  "chevron-end": ["chevron-right", '<path d="m9 18 6-6-6-6"/>'],
  "chevron-up": ["chevron-up", '<path d="m18 15-6-6-6 6"/>'],
  "chevron-down": ["chevron-down", '<path d="m6 9 6 6 6-6"/>'],
  "expand": ["chevrons-up-down", '<path d="m7 15 5 5 5-5"/><path d="m7 9 5-5 5 5"/>'],
  "collapse": ["chevrons-down-up", '<path d="m7 20 5-5 5 5"/><path d="m7 4 5 5 5-5"/>'],
  "lock": ["lock", '<rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>'],
  "unlock": ["lock-open", '<rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 9.9-1"/>'],
  "dashboard": ["layout-dashboard", '<rect width="7" height="9" x="3" y="3" rx="1"/><rect width="7" height="5" x="14" y="3" rx="1"/><rect width="7" height="9" x="14" y="12" rx="1"/><rect width="7" height="5" x="3" y="16" rx="1"/>'],
  "trades": ["list", '<path d="M3 5h.01"/><path d="M3 12h.01"/><path d="M3 19h.01"/><path d="M8 5h13"/><path d="M8 12h13"/><path d="M8 19h13"/>'],
  "copy-trader": ["network", '<rect x="16" y="16" width="6" height="6" rx="1"/><rect x="2" y="16" width="6" height="6" rx="1"/><rect x="9" y="2" width="6" height="6" rx="1"/><path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3"/><path d="M12 12V8"/>'],
  "recorder": ["video", '<path d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5"/><rect x="2" y="6" width="14" height="12" rx="2"/>'],
  "reports": ["chart-column", '<path d="M3 3v16a2 2 0 0 0 2 2h16"/><path d="M18 17V9"/><path d="M13 17V5"/><path d="M8 17v-3"/>'],
  "account": ["wallet", '<path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1"/><path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"/>'],
  "calendar": ["calendar", '<path d="M8 2v3"/><path d="M16 2v3"/><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18"/>'],
  "notification": ["bell", '<path d="M10.268 21a2 2 0 0 0 3.464 0"/><path d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"/>'],
  "notifying": ["bell-ring", '<path d="M10.268 21a2 2 0 0 0 3.464 0"/><path d="M22 8c0-2.3-.8-4.3-2-6"/><path d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"/><path d="M4 2C2.8 3.7 2 5.7 2 8"/>'],
  "bookmark": ["bookmark", '<path d="M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z"/>'],
  "like": ["heart", '<path d="M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"/>'],
  "star": ["star", '<path d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"/>'],
  "light": ["sun", '<circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/>'],
  "dark": ["moon", '<path d="M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401"/>'],
};

export const ICONS = Object.fromEntries(Object.entries(ICON_SOURCE).map(([meaning, [name]]) => [meaning, name]));

const escape = (value) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const source = (name) => {
  const found = ICON_SOURCE[name];
  if (!found) throw new Error(`Unknown icon "${name}"`);
  return found;
};

const fillOf = (name) => `<g class="ui-icon-fill" aria-hidden="true">${source(name)[1]}</g>`;

export function icon(name, { size, label, filled } = {}) {
  const naming = label ? `role="img" aria-label="${escape(label)}"` : 'aria-hidden="true"';
  return `<svg class="ui-icon" data-icon="${name}"${size ? ` data-size="${escape(size)}"` : ""}${filled ? " data-filled" : ""} viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" ${naming}>${source(name)[1]}${filled ? fillOf(name) : ""}</svg>`;
}

const fill = (svg, name, on) => {
  if (on && !svg.querySelector(".ui-icon-fill")) {
    svg.insertAdjacentHTML("beforeend", fillOf(name));
    void getComputedStyle(svg.lastElementChild).clipPath;
  }
  svg.toggleAttribute("data-filled", on);
};

const named = (svg, label) => {
  if (label) {
    svg.setAttribute("role", "img");
    svg.setAttribute("aria-label", label);
    svg.removeAttribute("aria-hidden");
  } else {
    svg.removeAttribute("role");
    svg.removeAttribute("aria-label");
    svg.setAttribute("aria-hidden", "true");
  }
};

customElements.define(
  "ui-icon",
  class extends HTMLElement {
    static observedAttributes = ["name", "label", "data-size", "data-morph", "data-filled"];
    connectedCallback() { this.render(); }
    attributeChangedCallback(attribute, before, after) {
      if (!this.isConnected || before === after) return;
      const svg = this.firstElementChild;
      if (svg && attribute === "data-filled") return fill(svg, this.getAttribute("name"), after !== null);
      if (!svg || !this.hasAttribute("data-morph")) return this.render();
      if (attribute === "label") return named(svg, after);
      if (attribute !== "name") return this.render();
      svg.dataset.icon = after;
      svg.querySelector(".ui-icon-fill")?.remove();
      morphGlyph(svg, source(after)[1]);
      if (this.hasAttribute("data-filled")) svg.insertAdjacentHTML("beforeend", fillOf(after));
    }
    render() {
      const name = this.getAttribute("name");
      this.innerHTML = icon(name, { size: this.dataset.size, label: this.getAttribute("label") });
      if (this.hasAttribute("data-morph")) drawGlyph(this.firstElementChild);
      if (this.hasAttribute("data-filled")) this.firstElementChild.insertAdjacentHTML("beforeend", fillOf(name));
      this.firstElementChild.toggleAttribute("data-filled", this.hasAttribute("data-filled"));
    }
  },
);
